### ISSUE TITLE
Leider kann ich kein Raiting abgeben. Es erscheint nur ein drehender Smiley.

### ISSUE THREAD

**Issue by MRothenburger** [punktDe/TYPO3.ext.th_rating#148]
Hallo,

ich verwende die Typo3 Verison 10.4.36

Ich kann leider kein Raiting abgeben. Es erscheint auch keine Fehlermeldung nur die Funktion "ajaxWait" verschindet nicht.
Es erscheint hier einfach nur ein lachender Smiley der sich im Kreis dreht.

Wird die Extension auch für die Typo3 v11 oder 12 weitergeführt?

Viele Grüße
Martina Rothenburger

**Comment by thucke** [comment]
Hallo @MRothenburger,

mir fehlt leider die Zeit, nebenberuflich den Support für die Erweiterung aufrecht zu erhalten sowie für neue Versionen weiterzuentwickeln.
Ich kann nicht einschätzen, ob sich die Situation später wieder ändert.
Daher biete ich die Erweiterung auch anderen Maintainern zu Übernahme an.

VG
T.Hucke
